services:
  db:
    image: postgres:13
    container_name: my_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - mailpit_network

  app:
    build: .
    container_name: fastapi_app
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
      MAIL_SERVER: mailpit 
      MAIL_PORT: 1025  
      MAIL_FROM: noreply@test.com
    depends_on:
      - db
      - mailpit
    ports:
      - "8000:8000"
    volumes:
      - ./alembic:/app/alembic  
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - mailpit_network

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: always
    ports:
      - "1025:1025" 
      - "8025:8025"  
    environment:
      - MAILPIT_UI=true
    networks:
      - mailpit_network
volumes:
  postgres_data:

networks:
  mailpit_network:
    driver: bridge